#!/usr/bin/env python3
import os
import sys

from analyzer import Analyzer
from termcolor import colored
from helpers import get_user_timeline

def main():

    # ensure proper usage
    if len(sys.argv) != 2:
        sys.exit("Usage: ./tweets @screen_name")

# get tweet(helper)
    if get_user_timeline != None:
        d = 3
    else:
        # check if successful
        sys.exit("failed to load")

    # error message(sys.exit)

# tokenize tweet
# initialize analyzer

# analyze tweets

if __name__ == "__main__":
    main()